---
title: "elo_joining"
author: "Alex Tidd"
format: html
---

```{r}
library(elo)
library(dplyr)
library(tidyverse)
library(cowplot)
library(ggrepel)
library(lubridate)
```

```{r}
schedule2324 <- read.csv("~/Desktop/SYE2024/schedule2324.csv")
```

```{r}
schedule2324 <- schedule2324 |>
  mutate(date = ymd(date))
```

```{r}
elo_ratings_initial <- tibble(home_team = schedule2324$home_team,
                              away_team = schedule2324$away_team,
                            elo_rating_home = 1500,
                            elo_rating_away = 1500,
                            outcome_home = schedule2324$outcome,
                            game_date = schedule2324$date)
```

```{r}
k = 20
elo_ratings_test_alternative <- elo_ratings_initial |> 
  mutate(outcome_away = abs(outcome_home - 1)) |> 
  mutate(exp_home = if_else(game_date == "2023-10-07",
                            true = 1/(1 + 10^((elo_rating_away - elo_rating_home)/400)),
                            false = NA)) |>
  mutate(exp_away = if_else(game_date == "2023-10-07",
                            true = 1/(1 + 10^((elo_rating_home - elo_rating_away)/400)),
                            false = NA)) |>
  mutate(elo_new_home = if_else(game_date == "2023-10-07",
                                true = elo_rating_home + 20*(outcome_home - exp_home),
                                false = elo_rating_home)) |>
  mutate(elo_new_away = if_else(game_date == "2023-10-07",
                                true = elo_rating_away + 20*(outcome_away - exp_away),
                                false = elo_rating_away))
```

```{r}
elo_ratings_pivot_teams<- elo_ratings_test_alternative |>
  pivot_longer(cols = c(home_team, away_team),
               names_to = "Locator", values_to = "team")
```

```{r}
elo_pivot_final <- elo_ratings_pivot_teams |>
  pivot_longer(cols = c(elo_rating_home, elo_rating_away),
               names_to = "elo_locator", values_to = "elo_ratings")
```

```{r}
elo_slice <- elo_pivot_final |>
  filter(Locator == "home_team") |>
  filter(elo_locator == "elo_rating_home")
```

```{r}
elo_slice_away <- elo_pivot_final |>
  filter(Locator == "away_team") |>
  filter(elo_locator == "elo_rating_away")
```


```{r}
elo_elo <- elo_slice |>
  mutate(elo = if_else(game_date > ymd("2023-10-07"),
                       true = NA,
                       false = elo_new_home)) |>
  group_by(team)|>
  fill(elo, .direction = "down") |>
  mutate(elo = if_else(elo == is.na(elo),
                       true = 1500,
                       false = elo))
```

```{r}
elo_elo_away <- elo_slice_away |>
  mutate(elo = if_else(game_date > ymd("2023-10-07"),
                       true = NA,
                       false = elo_new_away)) |>
  group_by(team)|>
  fill(elo, .direction = "down") |>
  mutate(elo = if_else(elo == is.na(elo),
                       true = 1500,
                       false = elo))
```


```{r}
elo_ratings_final_OCT7_home <- elo_elo |> 
  filter(game_date == "2023-10-07") |>
  select(team, elo_new_home, game_date)
```

```{r}
elo_ratings_final_OCT7_away <- elo_elo_away |> 
  filter(game_date == "2023-10-07") |>
  select(team, elo_new_away, game_date)
```

```{r}
ratings_update_home <- tibble(team = elo_elo$team,
                              rating = elo_elo$elo_new_home,
                              game_date = elo_elo$game_date) |> 
  filter(game_date == "2023-10-07") |>
  arrange(desc(rating))
ratings_updated_away <- tibble(team = elo_elo_away$team,
                              rating = elo_elo_away$elo_new_away,
                              game_date = elo_elo_away$game_date) |> 
  filter(game_date == "2023-10-07") |>
  arrange(desc(rating))

ratings_updated_07OCT24 <- bind_rows(ratings_update_home, ratings_updated_away) |>
  arrange(desc(rating))
```
